# Generated by Django 4.0 on 2022-01-18 21:42

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('image', models.ImageField(max_length=255, upload_to=settings.models.banner_image_uploader)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
