# Generated by Django 4.0 on 2022-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_banner_alter_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('Mini', 'Mini'), ('Large', 'Large')], default='Mini', max_length=150),
        ),
    ]
