# Generated by Django 4.0 on 2022-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_banner_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(help_text='Example: https://mysite.com/products/...'),
        ),
    ]
