# Generated by Django 4.0 on 2022-01-19 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_banner_title_alter_banner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', ckeditor.fields.RichTextField(verbose_name='About Website')),
                ('cover', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/CoverPost-image.png', verbose_name='Cover Post')),
                ('bg_cover', models.ImageField(blank=True, max_length=255, null=True, upload_to='about/background-image.png', verbose_name='Back Ground')),
                ('phone', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Website Details',
            },
        ),
    ]
