# Generated by Django 4.0 on 2022-01-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
