# Generated by Django 4.0 on 2022-01-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
