# Generated by Django 4.0 on 2022-01-26 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
